# Generated by Django 4.0.5 on 2023-02-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.blog'),
        ),
    ]
